# Generated by Django 5.0.4 on 2024-05-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('stories', '0001_initial'), ('stories', '0002_label_storylabel_story_labels'), ('stories', '0003_alter_label_type'), ('stories', '0004_alter_label_type_alter_story_labels'), ('stories', '0005_story_needssum'), ('stories', '0006_story_needsprimary')]

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('story', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('image', models.FileField(blank=True, upload_to='story_images/')),
                ('needsKnow', models.IntegerField(default=0)),
                ('needsUnderstand', models.IntegerField(default=0)),
                ('needsFeel', models.IntegerField(default=0)),
                ('needsDo', models.IntegerField(default=0)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('LOCATION', 'Locatie'), ('TOPIC', 'Onderwerp'), ('CATEGORY', 'Categorie'), ('AUDIENCE', 'Doelgroep')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StoryLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.label')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
            ],
            options={
                'unique_together': {('story', 'label')},
            },
        ),
        migrations.AddField(
            model_name='story',
            name='labels',
            field=models.ManyToManyField(blank=True, through='stories.StoryLabel', to='stories.label'),
        ),
        migrations.AddField(
            model_name='story',
            name='needsSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='needsPrimary',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
