# Generated by Django 5.0.4 on 2024-04-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('story', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('image', models.FileField(blank=True, upload_to='story_images/')),
                ('needsKnow', models.IntegerField(default=0)),
                ('needsUnderstand', models.IntegerField(default=0)),
                ('needsFeel', models.IntegerField(default=0)),
                ('needsDo', models.IntegerField(default=0)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
        ),
    ]
