# Generated by Django 5.0.4 on 2024-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_label_storylabel_story_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('TOPIC', 'Subject/Topic'), ('CATEGORY', 'Category'), ('AUDIENCE', 'Audience')], max_length=20),
        ),
    ]
