# Generated by Django 5.0.4 on 2024-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_squashed_0006_story_needsprimary'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
