# Generated by Django 5.0.4 on 2024-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylabel',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
