# Generated by Django 5.0.4 on 2024-06-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storylabel_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('LOCATION', 'Locatie'), ('TOPIC', 'Onderwerp')], max_length=20),
        ),
    ]
