# Generated by Django 5.0.4 on 2024-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('municipality', models.CharField(blank=True, max_length=200)),
                ('medium', models.CharField(blank=True, max_length=200)),
                ('originalContent', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Mix', 'Mix')], max_length=20)),
                ('releaseFrequency', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Changeable / Unsure', 'Unsure')], max_length=20)),
                ('commercialPublisher', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unsure', 'Unsure')], max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('individualOrOrganisation', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Organization', 'Organization'), ('Unsure', 'Unsure')], max_length=20)),
                ('contentType', models.CharField(blank=True, choices=[('Entertainment', 'Entertainment'), ('Journalism', 'Journalism'), ('Service provision', 'Service'), ('Mixed content', 'Mix'), ('Other content', 'Other')], max_length=20)),
                ('contentArea', models.CharField(blank=True, max_length=200)),
                ('contentQuality', models.CharField(blank=True, choices=[('Weak / poor', 'Low'), ('Okay, editor required', 'Medium'), ('Meets journalistic requirements', 'High')], max_length=50)),
            ],
        ),
    ]
