# Generated by Django 5.0.4 on 2024-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sources', '0001_initial'), ('sources', '0002_alter_source_commercialpublisher_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('municipality', models.CharField(blank=True, max_length=200)),
                ('medium', models.CharField(blank=True, max_length=200)),
                ('originalContent', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('MIX', 'Mix')], max_length=20)),
                ('releaseFrequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('UNSURE', 'Changeable / Unsure')], max_length=20)),
                ('commercialPublisher', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNSURE', 'Unsure')], max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('individualOrOrganisation', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('UNSURE', 'Unsure')], max_length=20)),
                ('contentType', models.CharField(blank=True, choices=[('ENTERTAINMENT', 'Entertainment'), ('JOURNALISM', 'Journalism'), ('SERVICE', 'Service provision'), ('MIX', 'Mixed content'), ('OTHER', 'Other content')], max_length=20)),
                ('contentArea', models.CharField(blank=True, max_length=200)),
                ('contentQuality', models.CharField(blank=True, choices=[('LOW', 'Weak / poor'), ('MEDIUM', 'Okay, editor required'), ('HIGH', 'Meets journalistic requirements')], max_length=50)),
            ],
        ),
    ]
