# Generated by Django 5.0.4 on 2024-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='commercialPublisher',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNSURE', 'Unsure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='contentQuality',
            field=models.CharField(blank=True, choices=[('LOW', 'Weak / poor'), ('MEDIUM', 'Okay, editor required'), ('HIGH', 'Meets journalistic requirements')], max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='contentType',
            field=models.CharField(blank=True, choices=[('ENTERTAINMENT', 'Entertainment'), ('JOURNALISM', 'Journalism'), ('SERVICE', 'Service provision'), ('MIX', 'Mixed content'), ('OTHER', 'Other content')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='individualOrOrganisation',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('UNSURE', 'Unsure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='originalContent',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('MIX', 'Mix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='releaseFrequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('UNSURE', 'Changeable / Unsure')], max_length=20),
        ),
    ]
