name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      TARGETPLATFORM: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Convert OWNER to lowercase
        run: echo "OWNER=$(echo $OWNER | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug

      - name: Create Buildx builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - name: Print TARGETPLATFORM
        run: echo "TARGETPLATFORM is $TARGETPLATFORM"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            TARGETPLATFORM=${{ env.TARGETPLATFORM }}
          tags: ghcr.io/${{ env.OWNER }}/news_hyperlocalizer:latest

      - name: Inspect the built image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.OWNER }}/news_hyperlocalizer:latest
