name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run and Check Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref != 'main')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --cov=./ --cov-report html --html=report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            report.html
            assets/style.css
            htmlcov/index.html
            htmlcov/style.css

      - name: Check Test Results
        run: |
          if grep -q 'data-test-result="fail"' report.html; then
            echo "Tests failed"
            exit 1
          else
            echo "All tests passed"
          fi