name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest --cov=./ --cov-report html --html=report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: | 
            report.html
            htmlcov/index.html

  check:
    name: Check Test Results
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Test Reports
        uses: actions/download-artifact@v2
        with:
          name: test-reports
          path: .

      - name: Check Test Results
        run: |
          if grep -q 'data-test-result="fail"' report.html; then
            echo "Tests failed"
            exit 1
          else
            echo "All tests passed"
          fi